# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_simplematrix')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_simplematrix')
    _simplematrix = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_simplematrix', [dirname(__file__)])
        except ImportError:
            import _simplematrix
            return _simplematrix
        if fp is not None:
            try:
                _mod = imp.load_module('_simplematrix', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _simplematrix = swig_import_helper()
    del swig_import_helper
else:
    import _simplematrix
del _swig_python_version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_method(set):
    def set_attr(self, name, value):
        if (name == "thisown"):
            return self.this.own(value)
        if hasattr(self, name) or (name == "this"):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


class SimpleMatrix(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, m, n):
        this = _simplematrix.new_SimpleMatrix(m, n)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def addToEntry(self, i, j, value):
        return _simplematrix.SimpleMatrix_addToEntry(self, i, j, value)

    def getEntry(self, i, j):
        return _simplematrix.SimpleMatrix_getEntry(self, i, j)

    def rank(self):
        return _simplematrix.SimpleMatrix_rank(self)
    num_rows = _swig_property(_simplematrix.SimpleMatrix_num_rows_get)
    num_columns = _swig_property(_simplematrix.SimpleMatrix_num_columns_get)

    def save(self, filename):
        return _simplematrix.SimpleMatrix_save(self, filename)

    def load(self, filename):
        return _simplematrix.SimpleMatrix_load(self, filename)
    __swig_destroy__ = _simplematrix.delete_SimpleMatrix
    __del__ = lambda self: None
SimpleMatrix_swigregister = _simplematrix.SimpleMatrix_swigregister
SimpleMatrix_swigregister(SimpleMatrix)

def is_null_product(M1, M2):
    return _simplematrix.is_null_product(M1, M2)
is_null_product = _simplematrix.is_null_product



