(TeX-add-style-hook "graphcomplex"
 (lambda ()
    (LaTeX-add-labels
     "cha:ribbon-graph-complex"
     "sec:moduli-spaces"
     "dfn:diff"
     "dfn:teichmuller"
     "dfn:mapping-class-group"
     "sec:Mgn"
     "sec:alternate-Mgn"
     "sec:moduli-space-stable"
     "sec:ribbon-graphs"
     "dfn:ribbon-graphs"
     "sec:contractions"
     "sec:rg-comb"
     "sec:rg-to-surfaces"
     "sec:embedded-rg"
     "dfn:embedded-rg"
     "lemma:morphism-of-embedded-rg"
     "sec:mgn-comb"
     "sec:atlas"
     "fig:sphere-retracts"
     "dfn:metric-ribbon-graphs"
     "fig:atlas"
     "fig:charts"
     "sec:strebel"
     "sec:mgn-comb-construction"
     "eq:rg-cells-moduli"
     "eq:rg-cells-teichmueller"
     "eq:kontsevich-4"
     "sec:arc-systems")))

