(TeX-add-style-hook "kontsevich"
 (lambda ()
    (LaTeX-add-labels
     "cha:kontsevich"
     "sec:witten-classes"
     "eq:intersection-index"
     "eq:positive-intersection"
     "eq:intersection-index-cpt"
     "dfn:F-and-Z"
     "eq:F-dfn"
     "eq:Z-dfn"
     "eq:F-dfn-cpt"
     "thm:kontsevich"
     "eq:K"
     "sec:calculation"
     "sec:wittens-classes-comb"
     "thm:comb-bundle"
     "sec:KMI"
     "eq:kontsevich-6"
     "eq:KMI"
     "eq:8"
     "eq:7"
     "eq:KMI-F"
     "sec:matrix-models"
     "thm:KMI-Z"
     "eq:KM"
     "eq:casimir"
     "eq:vertices")))

