(TeX-add-style-hook "rt"
 (lambda ()
    (LaTeX-add-labels
     "cha:rt"
     "sec:rt-diagrams"
     "RT1"
     "RT2"
     "RT3"
     "RT4"
     "RT5"
     "RT6"
     "RT7"
     "dfn:graph-composition"
     "fig:graph-composition"
     "fig:graph-otimes"
     "dfn:diagrams-category"
     "sec:rt-graphs"
     "lemma:moves"
     "fig:rrt"
     "thm:generators"
     "fig:struct"
     "thm:rt"
     "sec:rt-gc"
     "thm:rt1"
     "thm:rt2")))

